config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-node-endpoint:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-node-endpoint
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-green-hyrax.sh
        container: qc.acc_homey-celadon-koala
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-turquoise-impala.sh
        container: qc.doc_sleepy-black-husky
      github.com/madgeek-arc/eosc-node-endpoint git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-periwinkle-chihuahua.sh
        container: qc.doc_scanty-denim-snail
      github.com/madgeek-arc/eosc-node-endpoint markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-tomato-eel.sh
        container: qc.doc_skimpy-lime-bongo
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lemon-giraffe.sh
        container: qc.lic_greasy-sepia-wildebeest
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-myrtle-capuchin.sh
        container: qc.sty_scaly-lilac-schnauzer
      github.com/madgeek-arc/eosc-node-endpoint jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ivory-angora.sh
        container: qc.sty_shaky-cerise-akita
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cobalt-whale.sh
        container: qc.ver_skimpy-periwinkle-kiwi
timeout: 5400
